appId: "co.yaler.client"
productName: MassBrowser
directories:
  output: build/client
files:
  - "node_modules/"
  - "dist/"
  - "package.json"
publish:
  provider: github
  repo: MassBrowser
  owner: SPIN-UMass
  protocol: https
dmg:
  contents:
    - x: 410
      y: 150
      type: link
      path: "/Applications"
    - x: 130
      y: 150
      type: file
mac: 
  icon: "app/assets/icons/client/icon.icns"
win:
  icon: "app/assets/icons/client/icon.ico"
linux:
  icon: "app/assets/icons/client"
